"""Structured logging configuration for the application.

This module centralizes logging setup and request-id context propagation.
"""

from __future__ import annotations

import json
import logging
from contextvars import ContextVar, Token
from datetime import UTC, datetime
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Any

from app.config.settings import settings

_request_id_ctx_var: ContextVar[str] = ContextVar("request_id", default="-")

_DEFAULT_RECORD_ATTRS = {
    "args",
    "asctime",
    "created",
    "exc_info",
    "exc_text",
    "filename",
    "funcName",
    "levelname",
    "levelno",
    "lineno",
    "module",
    "msecs",
    "message",
    "msg",
    "name",
    "pathname",
    "process",
    "processName",
    "relativeCreated",
    "stack_info",
    "thread",
    "threadName",
}


class RequestContextFilter(logging.Filter):
    """Inject request correlation id into every log record.

    Example:
        >>> request_filter = RequestContextFilter()
        >>> isinstance(request_filter, logging.Filter)
        True
    """

    def filter(self, record: logging.LogRecord) -> bool:
        """Attach current request id to the log record.

        Args:
            record: Log record generated by the logger.

        Returns:
            ``True`` to keep record in logging pipeline.
        """
        record.request_id = get_request_id()
        return True


class JsonFormatter(logging.Formatter):
    """Serialize logs as JSON for easier indexing and searching."""

    def format(self, record: logging.LogRecord) -> str:
        """Build JSON log line for a given record.

        Args:
            record: Python logging record.

        Returns:
            Stringified JSON document.
        """
        log_payload: dict[str, Any] = {
            "timestamp": datetime.now(UTC).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
            "module": record.module,
            "function": record.funcName,
            "line": record.lineno,
            "process_id": record.process,
            "thread_id": record.thread,
            "request_id": getattr(record, "request_id", "-"),
        }

        extras = {
            key: value
            for key, value in record.__dict__.items()
            if key not in _DEFAULT_RECORD_ATTRS and not key.startswith("_")
        }
        if extras:
            log_payload["extra"] = extras

        if record.exc_info:
            log_payload["exception"] = self.formatException(record.exc_info)

        return json.dumps(log_payload, ensure_ascii=True, default=str)


def set_request_id(request_id: str) -> Token[str]:
    """Store request id in context for current execution flow.

    Args:
        request_id: Request id from header or generated fallback.

    Returns:
        Context token used to restore previous value.
    """
    return _request_id_ctx_var.set(request_id)


def reset_request_id(token: Token[str]) -> None:
    """Reset context variable to previous request id state.

    Args:
        token: Token returned by ``set_request_id``.

    Returns:
        None.
    """
    _request_id_ctx_var.reset(token)


def get_request_id() -> str:
    """Return current request id from context variable.

    Returns:
        Current request id or ``"-"`` when no request context exists.
    """
    return _request_id_ctx_var.get()


def configure_logging() -> None:
    """Configure structured logging with file rotation and console output.

    Rotation settings are controlled via environment variables and create
    up to ``settings.log_backup_count`` files under ``settings.log_directory``.

    Returns:
        None.

    Example:
        >>> configure_logging()
    """
    root_logger = logging.getLogger()
    if getattr(root_logger, "_ai_review_logging_configured", False):
        return

    logs_dir = Path(settings.log_directory)
    logs_dir.mkdir(parents=True, exist_ok=True)

    log_formatter = JsonFormatter()
    context_filter = RequestContextFilter()

    file_handler = RotatingFileHandler(
        filename=logs_dir / "application.log",
        maxBytes=settings.log_rotation_max_mb * 1024 * 1024,
        backupCount=settings.log_backup_count,
        encoding="utf-8",
    )
    file_handler.setFormatter(log_formatter)
    file_handler.addFilter(context_filter)

    stream_handler = logging.StreamHandler()
    stream_handler.setFormatter(log_formatter)
    stream_handler.addFilter(context_filter)

    root_logger.handlers.clear()
    root_logger.setLevel(settings.log_level.upper())
    root_logger.addHandler(file_handler)
    root_logger.addHandler(stream_handler)
    root_logger._ai_review_logging_configured = True
